source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


api_url = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include(api_url)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from webapp.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    ClientGroupUpdateView, ClientDeletedListView, ClientRestoreView,\
    PaymentCreateView,  PaymentUpdateView, PaymentDeleteView, \
    CoachListView, CoachDetailView, CoachCreateView, CoachUpdateView, CoachDeleteView, CoachStatisticsView,\
    GroupListView, GroupDetailView, GroupCreateView, GroupUpdateView, GroupDeleteView, \
    GroupClientUpdateView, GroupClientDeleteView, \
    TrainingListView, TrainingCreateView, TrainingDeleteView, \
    SendInvite, Mailing, GroupMailing, StatisticsView


app_name = 'webapp'

client_url = [
    path('', ClientListView.as_view(), name='index'),
    path('deleted/list', ClientDeletedListView.as_view(), name='deleted_list'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('<int:pk>/client/restore', ClientRestoreView.as_view(), name='client_restore'),
    path('<int:pk>/client/update', ClientGroupUpdateView.as_view(), name='client_group_update'),
]

payment_url = [
    path('<int:pk>/create/', PaymentCreateView.as_view(), name='payment_create'),
    path('<int:pk>/update/', PaymentUpdateView.as_view(), name='payment_update'),
    path('<int:pk>/delete/', PaymentDeleteView.as_view(), name='payment_delete'),
]

coach_url = [
    path('list/', CoachListView.as_view(), name='coach_list'),
    path('<int:pk>/detail/', CoachDetailView.as_view(), name='coach_detail'),
    path('create/', CoachCreateView.as_view(), name='coach_create'),
    path('<int:pk>/update/', CoachUpdateView.as_view(), name='coach_update'),
    path('<int:pk>/delete/', CoachDeleteView.as_view(), name='coach_delete'),
    path('statistics/', CoachStatisticsView.as_view(), name='coach_statistics'),

]

group_url = [
    path('list/', GroupListView.as_view(), name='group_list'),
    path('<int:pk>/detail/', GroupDetailView.as_view(), name='group_detail'),
    path('create/', GroupCreateView.as_view(), name='group_create'),
    path('<int:pk>/update/', GroupUpdateView.as_view(), name='group_update'),
    path('<int:pk>/delete/', GroupDeleteView.as_view(), name='group_delete'),
    path('<int:pk>/client/update', GroupClientUpdateView.as_view(), name='group_client_update'),
    path('<int:pk>/client/delete', GroupClientDeleteView.as_view(), name='group_client_delete'),
]


training_url = [
    path('<int:pk>/list/', TrainingListView.as_view(), name='training_list'),
    path('<int:pk>/create/', TrainingCreateView.as_view(), name='training_create'),
    path('<int:pk>/delete/', TrainingDeleteView.as_view(), name='training_delete'),
]

send_invitee_massage_url = [
    path('<int:pk>/invite/', SendInvite.as_view(), name='send_invite'),
    path('<int:pk>/group/', GroupMailing.as_view(), name='send_group_mailing'),
    path('mailing/', Mailing.as_view(), name='mailing_page'),
]

stats_url = [
    path('', StatisticsView.as_view(), name='statistics'),
]

urlpatterns = [
    path('', include(client_url)),
    path('client/', include(client_url)),
    path('payment/', include(payment_url)),
    path('coach/', include(coach_url)),
    path('group/', include(group_url)),
    path('training/', include(training_url)),
    path('send/', include(send_invitee_massage_url)),
    path('statistics/', include(stats_url)),
]

source/webapp/views/client_views.py
from datetime import datetime
from typing import Optional, Union
from django.core.exceptions import BadRequest
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.utils.http import urlencode
from django.urls import reverse, reverse_lazy
from django.db.models import Count, QuerySet
from django.db.models import Q
from django.contrib.auth.mixins import PermissionRequiredMixin
from webapp.models import Client
from webapp.forms import ClientForm, AddGroupClient, SearchForm
from webapp.filters import ClientFilter


class ClientListView(PermissionRequiredMixin, ListView):
    model = Client
    template_name: str = 'clients/clients_list.html'
    context_object_name: str = 'clients'
    paginate_by: int = 10
    ordering = '-created_at'
    permission_required = 'webapp.owner' and 'webapp.manager'

    def get_search_form(self) -> SearchForm:
        return SearchForm(self.request.GET)

    def get_search_value(self) -> Optional[str]:
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get(self, request, *args, **kwargs) -> Union[redirect, ListView]:
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.filter(is_active=True).annotate(visit_count=Count('trainings'))
        if self.search_value:
            queryset = queryset.filter(
                Q(telegram_id__icontains=self.search_value) | Q(phone__icontains=self.search_value) |
                Q(first_name__icontains=self.search_value) | Q(last_name__icontains=self.search_value) |
                Q(region__icontains=self.search_value))
        return ClientFilter(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['filter'] = ClientFilter(self.request.GET, queryset=self.get_queryset())
        context['form'] = self.form
        if self.request.GET.get('is_paid'):
            context['query'] = urlencode({'is_paid': self.request.GET.get('is_paid')})
        elif self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ClientCreateView(PermissionRequiredMixin, CreateView):
    model = Client
    form_class: ClientForm = ClientForm
    template_name: str = 'clients/client_create.html'
    permission_required = 'webapp.owner' and 'webapp.manager'

    def get_success_url(self) -> str:
        return reverse('webapp:client_detail', kwargs={'pk': self.object.pk})


class ClientDetailView(PermissionRequiredMixin, DetailView):
    model = Client
    template_name: str = 'clients/client_detail.html'
    permission_required = 'webapp.owner' and 'webapp.manager'
    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.annotate(visit_count=Count('trainings'))
        return queryset

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        client = self.get_object()
        payments = client.payments.order_by('-paid_at')
        paginator = Paginator(payments, 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        active_client = Client.objects.active_clients().filter(pk=client.pk)
        is_active_payment = payments.filter(payment_start_date__lte=datetime.now(),
                                            payment_end_date__gte=datetime.now()).exists()
        is_deleted = active_client.filter(is_active=False).exists()
        context['form'] = AddGroupClient() if active_client and not is_deleted and client.group is None else None
        context['page_obj'] = page_obj
        context['is_paginated'] = page_obj.has_other_pages()
        context['is_active_payment'] = is_active_payment
        context['payments'] = page_obj.object_list
        context['is_deleted'] = is_deleted
        return context


class ClientUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'clients/client_update.html'
    model = Client
    form_class = ClientForm
    permission_required = 'webapp.owner' and 'webapp.manager'
    def get_success_url(self) -> str:
        return reverse('webapp:client_detail', kwargs={'pk': self.object.pk})


class ClientDeleteView(PermissionRequiredMixin, DeleteView):
    template_name: str = 'clients/client_delete.html'
    model = Client
    context_object_name: str = 'client'
    success_url: str = reverse_lazy('webapp:index')
    permission_required = 'webapp.owner'
    def post(self, request, *args, **kwargs):
        client = get_object_or_404(Client, pk=int(kwargs.get('pk')))
        client.is_active = False
        client.group = None
        client.save()
        return redirect(self.success_url)


class ClientRestoreView(PermissionRequiredMixin, DeleteView):
    template_name: str = 'clients/client_restore.html'
    model = Client
    context_object_name: str = 'client'
    success_url: str = reverse_lazy('webapp:deleted_list')
    permission_required = 'webapp.owner' and 'webapp.manager'

    def post(self, request, *args, **kwargs):
        client = get_object_or_404(Client, pk=int(kwargs.get('pk')))
        client.is_active = True
        client.save()
        return redirect(self.success_url)


class ClientDeletedListView(PermissionRequiredMixin, ListView):
    model = Client
    template_name: str = 'clients/clients_deleted_list.html'
    context_object_name: str = 'clients'
    paginate_by: int = 10
    permission_required = 'webapp.owner' and 'webapp.manager'

    def get_search_form(self) -> SearchForm:
        return SearchForm(self.request.GET)

    def get_search_value(self) -> Optional[str]:
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get(self, request, *args, **kwargs) -> Union[redirect, ListView]:
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Client]:
        clients = super().get_queryset()
        queryset = clients.filter(is_active=False).annotate(visit_count=Count('trainings'))
        if self.search_value:
            queryset = queryset.filter(
                Q(telegram_id__icontains=self.search_value) | Q(phone__icontains=self.search_value))
        return ClientFilter(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['filter'] = ClientFilter(self.request.GET, queryset=self.get_queryset())
        context['form'] = self.form
        if self.request.GET.get('is_paid'):
            context['query'] = urlencode({'is_paid': self.request.GET.get('is_paid')})
        elif self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ClientGroupUpdateView(PermissionRequiredMixin, View):
    permission_required = 'webapp.owner' and 'webapp.manager'

    def post(self, request, *args, **kwargs) -> HttpResponse:
        client_pk: int = kwargs.get('pk')
        group_id: int = int(request.POST.get('group_id'))
        is_active: bool = Client.objects.active_clients().filter(pk=client_pk)
        client: Client = get_object_or_404(Client, pk=client_pk)
        if is_active and client.group is None:
            client.group_id = group_id
            client.save()
            return redirect(self.get_redirect_url(group_id))
        raise BadRequest('Клиент неактивен или уже состоит в группе')

    def get_redirect_url(self, group_pk: int) -> str:
        return reverse('webapp:group_detail', kwargs={'pk': group_pk})

source/webapp/views/coach_views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.db.models import Count, QuerySet
from django.contrib.auth.mixins import PermissionRequiredMixin
from webapp.models import Coach
from webapp.forms import CoachForm, CoachStatisticsPeriodForm


class CoachListView(PermissionRequiredMixin, ListView):
    model = Coach
    template_name: str = 'coaches/coach_list.html'
    context_object_name: str = 'coaches'
    paginate_by: int = 10
    permission_required = 'webapp.owner' and 'webapp.manager'


class CoachDetailView(PermissionRequiredMixin, DetailView):
    model = Coach
    template_name: str = 'coaches/coach_detail.html'
    context_object_name: str = 'coach'
    permission_required = 'webapp.owner' and 'webapp.manager'

    def get_context_data(self, **kwargs) -> dict:
        groups = self.get_object().groups.filter(is_active=True).all()
        return super().get_context_data(groups=groups, **kwargs)


class CoachCreateView(PermissionRequiredMixin, CreateView):
    model = Coach
    template_name: str = 'coaches/coach_create.html'
    form_class = CoachForm
    permission_required = 'webapp.owner' and 'webapp.manager'

    def get_success_url(self) -> str:
        return reverse('webapp:coach_detail', kwargs={'pk': self.object.pk})


class CoachUpdateView(PermissionRequiredMixin, UpdateView):
    model = Coach
    template_name: str = 'coaches/coach_update.html'
    form_class = CoachForm
    permission_required = 'webapp.owner' and 'webapp.manager'

    def get_success_url(self) -> str:
        return reverse('webapp:coach_detail', kwargs={'pk': self.object.pk})


class CoachDeleteView(PermissionRequiredMixin, DeleteView):
    model = Coach
    template_name: str = 'coaches/coach_delete.html'
    context_object_name: str = 'coach'
    success_url: str = reverse_lazy('webapp:coach_list')
    permission_required = 'webapp.owner'


class CoachStatisticsView(PermissionRequiredMixin, ListView):
    model = Coach
    template_name: str = 'coaches/coach_statistics.html'
    context_object_name: str = 'coaches'
    paginate_by: int = 10
    permission_required = 'webapp.owner' and 'webapp.manager'

    def get_queryset(self) -> QuerySet:
        start_date = self.request.GET.get('start_date')
        end_date = self.request.GET.get('end_date')
        coaches = super().get_queryset()
        if start_date and end_date:
            coaches = coaches.filter(
                coach_trainings__created_at__gte=start_date, coach_trainings__created_at__lte=end_date
            )
        queryset = coaches.annotate(quantity=Count('coach_trainings')).order_by('telegram_id')
        return queryset

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['form'] = CoachStatisticsPeriodForm(self.request.GET)
        return context

source/webapp/views/payments_views.py
from datetime import datetime, timedelta
from django.views.generic import CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.contrib.auth.mixins import PermissionRequiredMixin
from webapp.models import Client, Payment
from webapp.forms import PaymentForm, PaymentUpdateForm


class PaymentCreateView(PermissionRequiredMixin, CreateView):
    model = Payment
    form_class = PaymentForm
    template_name: str = 'payments/payment_create.html'
    permission_required = 'webapp.owner' and 'webapp.manager'

    def form_valid(self, form):
        client = get_object_or_404(Client, pk=self.kwargs.get('pk'))
        if not client.is_active:
            return HttpResponseBadRequest('Cannot create payment for deleted client.')
        form.instance.client = client
        if client.payments.exists():
            latest_payment = client.payments.latest('payment_end_date')
            payment_start_date = latest_payment.payment_end_date + timedelta()
        else:
            payment_start_date = datetime.now()
        payment_end_date = payment_start_date + timedelta(days=30)
        form.instance.payment_start_date = payment_start_date
        form.instance.payment_end_date = payment_end_date
        response = super().form_valid(form)
        client.save()
        return response

    def get_success_url(self):
        return reverse('webapp:client_detail', kwargs={'pk': self.object.client.pk})


class PaymentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Payment
    template_name: str = 'payments/payment_update.html'
    form_class = PaymentUpdateForm
    permission_required = 'webapp.owner' and 'webapp.manager'

    def get_success_url(self) -> str:
        return reverse('webapp:client_detail', kwargs={'pk': self.object.client.pk})


class PaymentDeleteView(PermissionRequiredMixin, DeleteView):
    model = Payment
    template_name = 'payments/payment_delete.html'
    permission_required = 'webapp.owner'

    def form_valid(self, form):
        success_url = self.get_success_url()
        payment = self.get_object()
        client = payment.client
        client.save()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def get_success_url(self) -> str:
        return reverse('webapp:client_detail', kwargs={'pk': self.object.client.pk})

source/webapp/templates/clients/client_create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Добавить нового клиента: </h1>
     <form action="" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Добавить" %}
    </form>
{% endblock %}

source/webapp/templates/clients/client_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="text-center fs-1 m-3 p-3">Вы действительно хотите удалить "{{ client.telegram_id }}"?</h1>
    <form method="POST" action="{% url 'webapp:client_delete' client.pk %}" class="text-center">
        {% csrf_token %}
        <button type="submit" class="sbmt_btn mr-3">Да</button>
        <a class="sbmt_btn" href="{% url 'webapp:client_detail' client.pk%}" role="button">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/clients/client_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Просмотр клиента{% endblock %}

{% block topbar %}
    {% if not is_deleted %}

        <li class="nav-item">
            <a class="nav_btn my-2" aria-current="page" href="{% url 'webapp:payment_create' client.pk %}">
                Добавить новый платёж
            </a>
        </li>

        {% if is_active_payment %}
            <li class="nav-item">
                {% include 'trainings/training_create.html' with button_text='Добавить тренировку' %}
            </li>
        {% endif %}

        <li class="nav-item">
            <a class="nav_btn my-2" aria-current="page" href="{% url 'webapp:training_list' client.pk %}">
                Тренировки
            </a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    {% include 'partial/freeze_modal.html' %}
    <div class="card m-5">
        <div class="row no-gutters">
            <div class="col-md-4">
                {% if client.photo %}
                    <div class="col-md-16">
                        <img src="{{ client.photo.url }}" class="card-img">
                    </div>
                {% else %}
                    <div class="col-md-16">
                        <img src="{% static "images/no_photo.jpg" %}" class="card-img">
                    </div>
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title d-flex align-items-center">
                        {% if not client.first_name %}
                            <span class="text-success">Новый клиент</span>
                        {% else %}
                            Имя: {{ client.first_name }}
                        {% endif %}
                        <p class="card-text ml-auto">
                            <a class="mx-2" href="{% url 'webapp:client_update' client.pk %}"><i
                                    class="bi bi-pencil"></i></a>
                            {% if perms.webapp.owner %}
                                <a href="{% url 'webapp:client_delete' client.pk %}"><i
                                        class="bi bi-trash3-fill"></i></a>
                            {% endif %}
                            {% if client.payments.all %}
                                {% with latest_payment=client.payments.last %}
                                    {% now "Y-m-d" as todays_date %}
                                    {% if todays_date < latest_payment.payment_end_date|date:"Y-m-d" %}
                                        <a class="freeze-btn mx-2" data-client-id="{{ client.pk }}" href="#"><i
                                                class="bi bi-snow"></i></a>
                                    {% endif %}
                                {% endwith %}
                            {% endif %}
                        </p>

                    </h4>
                    <div class="ms-auto">

                    </div>
                    {% if not client.last_name %}
                        <p class="card-text">Фамилия: --</p>
                    {% else %}
                        <p class="card-text">Фамилия: {{ client.last_name }}</p>
                    {% endif %}
                    {% if not client.group %}
                        <p class="card-text">Группа: --</p>
                    {% else %}
                        <p class="card-text">Группа: <a
                                href="{% url 'webapp:group_detail' client.group.pk %}">{{ client.group.name }}</a></p>
                    {% endif %}
                    <p class="card-text">Telegram: {{ client.telegram_id }}</p>
                    {% if not client.email %}
                        <p class="card-text">Почта: --</p>
                    {% else %}
                        <p class="card-text">Почта: {{ client.email }}</p>
                    {% endif %}
                    {% if not client.phone %}
                        <p class="card-text">Телефон: --</p>
                    {% else %}
                        <p class="card-text">Телефон: {{ client.phone }}</p>
                    {% endif %}

                    {% if not client.region %}
                        <p class="card-text">Регион: --</p>
                    {% else %}
                        <p class="card-text">Регион: {{ client.region }}</p>
                    {% endif %}
                    <p class="card-text">Количество посещений: {{ client.visit_count }}</p>
                    {% if not client.comment %}
                        <p class="card-text">Комментарий: --</p>
                    {% else %}
                        <p class="card-text">Комментарий: {{ client.comment }}</p>
                    {% endif %}
                    <p class="card-text">Дата добавления: {{ client.created_at|date:"d M Y" }}</p>
                </div>
            </div>
        </div>
    </div>


    {% if form %}
        <form action="{% url 'webapp:client_group_update' client.pk %}" method="POST">
            {% include 'partial/form.html' with button_text="Добавить" %}
        </form>
    {% endif %}

    {% for payment in payments %}
        <div class="card m-3">
            <div class="card-body">
                <h3 class="card-title">Платёж:
                    <a href="{% url 'webapp:payment_update' payment.pk %}" class="cng_btn ml-4"><i
                            class="bi bi-pencil"></i></a>
                    {% if perms.webapp.owner %}
                        <a href="{% url 'webapp:payment_delete' payment.pk %}" class="cng_btn ml-3"><i
                                class="bi bi-trash3-fill"></i></a>
                    {% endif %}
                </h3>
                <p class="card-text">Сумма оплаты: {{ payment.amount }} </p>
                <p class="card-text">Дата начала абонемента: {{ payment.payment_start_date|date:"d M Y" }} </p>
                <p class="card-text">Дата окончания абонемента: {{ payment.payment_end_date|date:"d M Y" }} </p>
                <p class="card-text">Дата оплаты: {{ payment.paid_at|date:"d M Y" }}</p>

                {% for lazy_day in payment.lazy_days.all %}
                    <hr>
                    <p class="card-text">Дата начала заморозки: {{ lazy_day.start_date|date:"d M Y" }} </p>
                    <p class="card-text">Дата окончания заморозки: {{ lazy_day.end_date|date:"d M Y" }} </p>
                    <hr>
                {% endfor %}

            </div>
        </div>

    {% empty %}
        <p>У этого клиента нет платежей.</p>
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

{% block js %}
    <script type="module" src="{% static 'js/freeze.js' %}"></script>
    <script type="module" src="{% static 'js/mailing.js' %}"></script>
{% endblock %}

source/webapp/templates/clients/client_restore.html
{% extends "base.html" %}

{% block content %}
    <h1 class="text-center fs-1 m-3 p-3">Вы действительно хотите восстановить "{{ client.telegram_id }}"?</h1>
    <form method="POST" action="{% url 'webapp:client_restore' client.pk %}" class="text-center">
        {% csrf_token %}
        <button type="submit" class="sbmt_btn">Да</button>
        <a class="sbmt_btn" href="{% url 'webapp:deleted_list' %}" role="button">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/clients/client_update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Изменить данные клиента: </h1>
     <form action="" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Изменить" %}
    </form>
{% endblock %}

source/webapp/templates/clients/clients_deleted_list.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="card-title text-center m-3 p-3">Удаленные клиенты</h1>
    {% include 'partial/partial_client_list_deleted.html' %}
{% endblock %}

source/webapp/templates/clients/clients_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h1 class="card-title text-center mt-3 pt-3">Клиенты</h1>

    <div class="d-flex justify-content-end mb-3">
        <h3 class="my-2">Всего: <span id="total-count"></span></h3>
        <label for="date-picker"></label>
        <input class="m-2" type="date" id="date-picker" name="date">
        <button id="submit-btn" class="sbmt_btn">Применить</button>
    </div>

    {% include 'partial/partial_client_list.html' %}
{% endblock %}

{% block js %}
    <script type="module" src="{% static 'js/total_active_clients.js' %}"></script>
    <script type="module" src="{% static 'js/freeze.js' %}"></script>
{% endblock %}